sudo: required
services:
  - docker

before_install:
  - docker build -t rmnlaiacona/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rmnlaiacona/react-test npm test

after_success:
  - docker build -t rmnlaiacona/mult-client ./client
  - docker build -t rmnlaiacona/multi-nginx ./nginx
  - docker build -t rmnlaiacona/multi-server ./server
  - docker build -t rmnlaiacona/multi-worker ./worker
    # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
  - docker push rmnlaiacona/multi-client
  - docker push rmnlaiacona/multi-nginx
  - docker push rmnlaiacona/multi-server
  - docker push rmnlaiacona/multi-worker
